### ISSUE TITLE
Binary file gets corrupted

### ISSUE THREAD

**Issue by juhamust** [chenasraf/simple-scaffold#40]
Binary files like jpegs are no longer valid after copying them.

**To Reproduce**

1. Template folders & files
    ```
    templates/
      another.jpg
    ```
2. Run with args/config:
    ```
    npx simple-scaffold -o output output-huz --templates templates/**/*  --name huz
    ```
**Expected behavior**
Binary files should be copied as-is. According to logs, it does so, but the output is corrupted.

**Logs**

```
process.cwd(): /Users/juha/Projects
origTemplate: simple-scaffold-test/templates/**/*
relPath: .
template: simple-scaffold-test/templates/**/*
inputFilePath: simple-scaffold-test/templates/another.jpg
nonGlobTemplate: simple-scaffold-test/templates/
basePath:
isDirOrGlob: true
isGlob: true


Parsing simple-scaffold-test/templates/another.jpg
Base path:
Full input path: /Users/juha/Projects/simple-scaffold-test/templates/another.jpg
Output Path Opt: output-huz
Full output dir: /Users/juha/Projects/output-huz
Full output path: /Users/juha/Projects/output-huz/another.jpg

Creating dir /Users/juha/Projects/output-huz
Writing to /Users/juha/Projects/output-huz/another.jpg
Error: Lexical error on line 1. Unrecognized text.
����JFIFHH��j
----^ {} Error: Lexical error on line 1. Unrecognized text.
����JFIFHH��j
----^
    at Parser.parseError (/Users/juha/.npm/_npx/8874/lib/node_modules/simple-scaffold/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
    at Object.parseError (/Users/juha/.npm/_npx/8874/lib/node_modules/simple-scaffold/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:394:36)
    at Object.next (/Users/juha/.npm/_npx/8874/lib/node_modules/simple-scaffold/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:522:33)
    at Object.lex (/Users/juha/.npm/_npx/8874/lib/node_modules/simple-scaffold/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:526:30)
    at lex (/Users/juha/.npm/_npx/8874/lib/node_modules/simple-scaffold/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:297:36)
    at Parser.parse (/Users/juha/.npm/_npx/8874/lib/node_modules/simple-scaffold/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:320:34)
    at parseWithoutProcessing (/Users/juha/.npm/_npx/8874/lib/node_modules/simple-scaffold/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:33)
    at HandlebarsEnvironment.parse (/Users/juha/.npm/_npx/8874/lib/node_modules/simple-scaffold/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:52:13)
    at compileInput (/Users/juha/.npm/_npx/8874/lib/node_modules/simple-scaffold/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:508:19)
    at ret (/Users/juha/.npm/_npx/8874/lib/node_modules/simple-scaffold/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:517:18)
Couldn't parse file with handlebars, returning original content
Done.
```

**Desktop (please complete the following information):**
 - OS: MacOS
- Node.js: 14.17.0
- Simple Scaffold Version: Using npx, assuming 1.1.1? Btw. app could print its version on help

**Additional context**

**Comment by chenasraf** [comment]
Thanks for the report @juhamust! I'm sorry you are experiencing this problem.

I will reproduce and try to fix the problem as soon as possible, and I'll update you when I have found a fix.

**Comment by chenasraf** [comment]
@juhamust Should be fixed in the current release (1.1.2), also added a test so it doesn't happen again (happened before, then I accidentally added a regression).

Please let me know if you have more problems! I will close this issue after you confirm it is fixed for you.

**Comment by juhamust** [comment]
@chenasraf thanks for the quick response and resolve time, again! 👍  I'll be sure to verify this today!

**Comment by chenasraf** [comment]
No problem, I also added the version in the help as you suggested :)

**Comment by chenasraf** [comment]
@juhamust I saw that, thank you very much! Incredibly appreciated. <3
